services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=cryptorecommenddb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=cryptorecommend
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - docker_network
  xm-prices-loader:
    build: ./prices-loader
    image: crypto-prices-loader
    pull_policy: build
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/cryptorecommenddb
      prices.loader.source: /sample_data
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - docker_network
    volumes:
      - ./sample_data:/sample_data
  xm-prices-app:
    build: ./prices-recommendation
    image: crypto-prices-app
    pull_policy: build
    ports:
      - 8080:8080
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/cryptorecommenddb
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - docker_network
networks:
  docker_network:
    driver: bridge